name: act-L1-local

on:
  workflow_dispatch:

jobs:
  trigger-L1:
    name: Trigger L1-tests.yml locally via act
    uses: ./.github/workflows/L1-tests.yml
    with:
      caller_source: local
    secrets:
      # act requires some value for required workflow_call secrets. For local runs, a dummy is fine
      # as long as the workflow doesn't actually need to fetch private repos.
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
